# This is a basic workflow to help you get started with Actions

name: Deploy Proto Library to Nuget

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  release_version: 1.0.7

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "C# Deployment"
  csharp_deployment:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup .NET Core 5.0.x
      - name: Setup .NET Core SDK '5.0.x'
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.x'

      # Install Protoc
      - name: Install Latest Protoc
        run: |
          sudo apt update
          sudo apt install -y protobuf-compiler
      
      # Do work script
      - name: Execute CSharp Release Script
        run: |
          chmod a+x ./release.sh
          ./release.sh ${{ env.release_version }} ${{ secrets.LWSAPIKEY }}
